services:
  redis:
    image: redis:7
    container_name: lp-redis
    ports:
      - "6379:6379"

  mqtt:
    image: eclipse-mosquitto:2
    container_name: lp-mqtt
    ports:
      - "1883:1883"

  gateway:
    build: .
    container_name: lowpower-tcp-gateway
    depends_on:
      - redis
      - mqtt
    ports:
      - "9000:9000"
      - "8080:8080"
    volumes:
      - ./config.json:/app/config.json:ro